### ISSUE TITLE
It seems can't surport matrix, align, split etc. properly

### ISSUE THREAD

**Issue by iamliukaifang** [arektekieli/FlaJax#3]
I want to display the following math formula, but failed~ any solution, please?

`$$ A = \begin{bmatrix}
        0 & 0 & 0 \\ 0 & 0 & -1\\ 0 & 1 & 0
    \end{bmatrix} $$`

`$$\begin{align*}
x& = y_1-y_2+y_3-y_5+y_8-\dots && \text{by ..}\\
& = y'\circ y^* && \text{(by ..)}\\
& = y(0) y' && \text {by Axiom 1.}
\end{align*} $$`

**Comment by arektekieli** [comment]
First of all Automatic Line Breaking is not supported in MathJax 3 according to: http://docs.mathjax.org/en/latest/output/linebreaks.html but I have managed to fix your first example by escaping backslashes:
```
$$ A = \begin{bmatrix} 0 & 0 & 0 \\\\ 0 & 0 & -1\\\\ 0 & 1 & 0 \end{bmatrix} $$
```

Your second example is most likely caused by FlaJax plugin colliding with Markdown plugin and you can fix this either by disable Markdown plugin or by escape parts of your math formula as follows:
```
$$\begin{align\*} x& = y_1-y_2+y_3-y_5+y_8-\dots && \text{by ..}\\ & = y'\circ y^* && \text{(by ..)}\\ & = y(0) y' && \text {by Axiom 1.} \end{align\*} $$
```
or
```
$$\begin{align} x& = y_1-y_2+y_3-y_5+y_8-\dots && \text{by ..}\\ & = y'\circ y^* && \text{(by ..)}\\ & = y(0) y' && \text {by Axiom 1.} \end{align} $$
```

**Comment by iamliukaifang** [comment]
Hi arektekieli,

Thanks very much for your comments. 

- first example is nicely correct now!
- the second seems still doesn't work, but I make it like this (two more back slash based on yours) and it works: $$\begin{align\*} x& = y_1-y_2+y_3-y_5+y_8-\dots && \text{by ..}\\\\ & = y'\circ y^* && \text{(by ..)}\\\\ & = y(0) y' && \text {by Axiom 1.} \end{align\*} $$

So the problems are solved. 
However, could you improve FlaJax to make it perfect for math formula (tex actually), because I'm not the only one hoping that. The first stable version of Flarum seems will come out soon, which could make it more popular, and a good extension for math seems important for some people.

I don't know js at all, but I would like to test the new version if you update it in the near future. Thank you again for your effort!

**Comment by arektekieli** [comment]
Yes, it is on my todo list to make it compatible in the future. For now i made it compatible with Flarum 1.0 release.
